export const baseUrl = 'http://127.0.0.1:8000/api';
export const REGISTER = 'auth/register';
export const LOGIN = 'auth/login';
export const REFRESH = 'auth/refresh';
export const UPDATE_AUTH = 'auth/update';
export const GOOGLE_CALL_BACK = "auth/google/callback"
export const LOGOUT = 'auth/logout';
export const USER = 'auth/user'; 
export const GOAL_INDEX = "goal/index";
export const PLAN_INDEX ='plan/index'
export const MY_GOAL = 'target/index'
export const MY_PLAN = 'target/plans'
export const GYM = 'gym/index';