export {default as Login} from './Components/Auth/Login/Login'
export {default as SignUp} from './Components/Auth/SignUp/SignUp'
export {default as Auth} from './Pages/Auth/Auth'
export {default as Size} from './Components/Information/Size/Size'
export {default as Address} from './Components/Information/Address/Address'
export {default as GoogleCallBack} from './Pages/Auth/GoogleCallBack/GoogleCallBack'
export {default as Loading} from './Components/Loading/Loading'
export {default as RequierAuth} from '../Auth/RequierAuth'
export {default as RequierBack} from '../Auth/RequierBack'
export {default as E404} from './Components/E404/E404'
export {default as Information} from './Pages/Information/Information'
export {default as Home} from './Pages/Home/Home'
export {default as Hero} from './Components/Home/Hero/Hero'
export {default as About} from './Components/Home/About/About'
export {default as Goal} from './Components/Home/Goal/Goal'
export {default as Plan} from './Components/Home/Plan/Plan'
export {default as Header} from './Layout/Header/Header'
export {default as Footer} from './Layout/Footer/Footer'
export {default as Main} from './Pages/Main/Main'
export {default as BuutonLoading} from './Components/Loading/ButtonLoading/ButtonLoading'
// export redux 
export {default as ActAuthLogin} from '../Redux/Auth/AuthSlice'
export {default as ActAuhSignUp} from '../Redux/Auth/AuthSlice'
// export custem hook
export {default as UseCheckEmail} from './Hooks/UseCheckEmail'
// export Scema
export {default as SignUpScema} from './Validation/SignUpScema'
export {default as LoginScema} from './Validation/LoginScema'
export {default as PaymentScema} from './Validation/PaymentScema'
// export images
export {default as Hero_1} from '../img/image.png'
export {default as Hero_2} from '../img/h-circle-one.png'
export {default as Hero_3} from '../img/h-circle-two.png'
export {default as Hero_4} from '../img/heart-rate.svg'
export {default as Hero_5} from '../img/calories.svg'
export {default as About_1} from '../img/a-banner.png'
export {default as About_2} from '../img/circle-one.png'
export {default as About_3} from '../img/circle-two.png'
export {default as About_4} from '../img/fitness.png'
export {default as About_5} from '../img/about-coach.jpg'
export {default as Goal_1} from '../img/classes-bg.png'
export {default as Goal_2} from '../img/class-i-1.png'
export {default as Goal_3} from '../img/class-i-2.png'
export {default as Goal_4} from '../img/class-i-3.png'
export {default as Goal_5} from '../img/class-i-4.png'
export {default as Goal_6} from '../img/class-one.jpg'
export {default as Goal_7} from '../img/class-two.jpg'
export {default as Goal_8} from '../img/class-three.jpg'
export {default as Plan_1} from '../img/blog-one.jpg'
export {default as Plan_2} from '../img/blog-two.jpg'
export {default as Plan_3} from '../img/blog-three.jpg'
export {default as Bg_Image} from '../img/hero-bg.png'
export {default as image_chat_1} from '../img/—Pngtree—fitness fitness equipment fitness equipment_3827338.png'
export {default as image_chat_2} from '../img/—Pngtree—cat gym fitness workout because_15588985.png'